# Introduction to Block Matrices

Block matrices are matrices composed of smaller sub-matrices, known as blocks. They are useful for efficiently performing operations on large datasets by breaking them down into smaller, more manageable pieces.

For some of the operations, we will need SciPy, a Python library used for scientific and technical computing. SciPy builds on NumPy and provides additional functionality, particularly for linear algebra, optimization, integration, and more. It will be especially useful for advanced matrix operations that are not available in NumPy. 

**Table of contents**

* [Basic Block Matrix Construction](#block)
* [Stacking and Tiling Matrices](#stacking)
* [Block Diagonal Matrices](#diagonal)

In [3]:
import numpy as np

## 1. BASIC BLOCK MATRIX CONSTRUCTION IN NUMPY <a class="anchor" id="block"></a>

Let's start by constructing block matrices using NumPy.

In [7]:
# Create smaller matrices (blocks)
A11 = np.array([[1, 2, 3], [4, 5, 6]])
A12 = np.array([[1,0], [0, 2]])
A21 = np.array([[3, 2, 1], [6, 5, 4]])
A22 = np.array([[7, 8], [9, 10]])

# Combine blocks into a block matrix
A = np.block([[A11, A12], [A21, A22]])
A

array([[ 1,  2,  3,  1,  0],
       [ 4,  5,  6,  0,  2],
       [ 3,  2,  1,  7,  8],
       [ 6,  5,  4,  9, 10]])

## 2. STACKING AND TILING MATRICES <a class="anchor" id="stacking"></a>

Using `np.vstack`, `np.hstack`, and `np.tile` for more advanced block matrix operations.

In [18]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9,10], [11, 12]])

We use `np.vstack` to stack matrices vertically.

In [19]:
# vertical stacking
np.vstack((A, B, C))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

We use `np.hstack` to stack matrices horizontally.

In [20]:
# horizontal stacking
np.hstack((A, B, C))

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

We use `np.tile` to repeat a matrix multiple times along specified dimensions.

In [21]:
# repeat matrix A three times along the vertical dimension and twice along the horizontal dimension.
np.tile(A, (3, 2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

## 3. BLOCK DIAGONAL MATRICES <a class="anchor" id="diagonal"></a>

Block diagonal matrices have smaller matrices on their diagonal, with zeros elsewhere.

In [23]:
from scipy.linalg import block_diag

# Create smaller matrices (blocks)
D1 = np.array([[1, 2, 3], [4, 5, 6]])
D2 = np.array([[7, 8], [9, 10]])
D3 = np.array([[11,12],[13,14],[15,16]])

# Combine blocks into a block diagonal matrix
D = block_diag(D1, D2, D3)
D

array([[ 1,  2,  3,  0,  0,  0,  0],
       [ 4,  5,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  8,  0,  0],
       [ 0,  0,  0,  9, 10,  0,  0],
       [ 0,  0,  0,  0,  0, 11, 12],
       [ 0,  0,  0,  0,  0, 13, 14],
       [ 0,  0,  0,  0,  0, 15, 16]])