# KRONECKER AND HADAMARD PRODUCTS

This notebook covers the Kronecker and Hadamard products, which are useful for various matrix operations in scientific computing.

**Table of contents**

* [The Kronecker Product](#kronecker)
* [The Hadamard Product](#hadamard)

In [1]:
import numpy as np

## 1. THE KRONECKER PRODUCT <a class="anchor" id="kronecker"></a>

The Kronecker product is a block matrix resulting from the multiplication of each element of a matrix by another matrix.
We use `np.kron` to compute the Kronecker product of two matrices

In [3]:
# Create smaller matrices (blocks)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [4]:
# # Kronecker product of A and B
np.kron(A,B)

array([[ 5,  6, 10, 12],
       [ 7,  8, 14, 16],
       [15, 18, 20, 24],
       [21, 24, 28, 32]])

In [5]:
# Kronecker product of B and A
np.kron(B,A)

array([[ 5, 10,  6, 12],
       [15, 20, 18, 24],
       [ 7, 14,  8, 16],
       [21, 28, 24, 32]])

## 2. THE HADAMARD PRODUCT <a class="anchor" id="hadamard"></a>

The Hadamard product is the element-wise product of two matrices of the same dimensions. You can use `*` for this operation.

In [6]:
# Hadamard product of A and B
A*B

array([[ 5, 12],
       [21, 32]])