#  THE LIBRARY NUMPY

 NumPy is a fundamental Python library for data analysis. The word NumPy stands for Numerical Python. The main focus of this library is on (multidimensional) arrays. An array is an object that can be used to store data. Examples of arrays are vectors and matrices.  This package is very appropriate to do math, and uses a language similar to Matlab. 

## **Table of contents:**

* [Importing the NumPy library](#import)
* [How to create a NumPy array](#numpyarray)
    * [Zero-dimensional arrays](#0-dimension)
    * [One-dimensional arrays](#1-dimension)
    * [Two-dimensional arrays](#2-dimension)
    * [Higher-dimensional arrays](#higher-dimension)
    * [The empty array](#emptyarray)
    * [Transforming the data type of the elements of an array](#arraysdata)
    * [Generating a random array](#random)
* [Dimension, shape and size of an array](#dimshapesize)
    * [Dimension of an array](#dimension)
    * [Shape of an array](#shape)
    * [Size of an array](#size)
    * [Reshaping an array](#reshaping)
* [Array indexing and slicing](#indexing-slicing)
    * [Indexing](#indexing)
    * [Slicing](#slicing)
* [Array iteration](#iteration)
* [Concatenation of arrays](#concatenation)
* [Sorting an array](#sorting)
* [Creating a copy of an array](#copy-array)
* [Universal functions](#universalfunctions)
    * [Component-wise arithmetic operations with arrays](#operations)
    * [Other useful functions defined on arrays](#otherfunctions)
* [The NumPy Linalg functions](#linalg)
    * [Special matrices](#special)
    * [Operations with matrices and vectors](#operations-matrices)
    * [The determinant of a matrix and its trace.](#determinant-trace)
    * [Rank of a matrix](#rank)
* [The functions linspace and arange](#linspace)

# 1. IMPORTING THE NUMPY LIBRARY <a class="anchor" id="import"></a>

In order to access the NumPy library or any other, we need to import it. For doing so, we use the code "import".

In [1]:
import numpy

In practice, in order to make the code more efficient, we give the Numpy library a shorter name. The traditional such name  is "np", although any other word could be used. 

In [4]:
import numpy as np

# 2. HOW TO CREATE A NUMPY ARRAY <a class="anchor" id="numpyarray"></a>

As we mentioned above, the main goal of the NumPy library is to work with arrays. In order to create an array, we use the function np.array(). Note that arrays are a new data type, namely, 'ndarrays".

## 2.1 Zero-dimensional arrays  <a class="anchor" id="0-dimension"></a>

A zero dimensional array is just a number. Let us see an example. We show that the resulting object is an ndarray.

In [43]:
a= np.array(3)
print(a)
type(a)

3


numpy.ndarray

## 2.1 One-dimensional arrays <a class="anchor" id="1-dimension"></a>

Let us see how to create a 1-dimensional array. We could start with a list and then apply the funcion "np.array(list)". By doing so we are changing the data type of the list to ndarray.

In [4]:
list1=[1,2,3,4]
a=np.array(list1)
print(a)
type(a)

[1 2 3 4]


numpy.ndarray

We could have also created the array directly as follows. 

In [4]:
a=np.array([1,2,3,4])
print(a)                   
type(a)

[1 2 3 4]


numpy.ndarray

The list to generate the array could potentially have length 1. Notice that our next example is a 1-dimensional array. Compare it with the zero-dimensional array provided in the previous section.

In [60]:
a2=np.array([3])
print(a2)
type(a2)

[3]


numpy.ndarray

It is also possible to create an array from a tuple or set. 

In [5]:
tuple=(1,2,3,4)
b=np.array(tuple)
print(b)
type(b)

[1 2 3 4]


numpy.ndarray

In [6]:
set={1,2,3,4}
c=np.array(set)
print(c)
type(c)

{1, 2, 3, 4}


numpy.ndarray

The elements of an array can be of different data types, as we see in the following examples. 

In [10]:
d=np.array([4,2,3, True])
print(d)
type(d)

[4 2 3 1]


numpy.ndarray

In [11]:
e=np.array([2,3,6, False])
print(e)

[2 3 6 0]


In [12]:
f=np.array([2, 4,6, 'hello'])
print(f)

['2' '4' '6' 'hello']


It is worth noting that, from a numerical point of view, it is more convenient to work with 1-dimensional arrays than with lists.  

## 2.2 Two-dimensional arrays. <a class="anchor" id="2-dimension"></a>

We can create "higher-dimensional" arrays by creating arrays, whose elements are arrays. Let us see an example of a 2-dimensional array. Here we show how to create two-dimensional arrays, namely, matrices. We start by producing two lists, which will be the rows of the matrix. 

In [13]:
list1=[9,8,7]
list2=[6,5,4]

g=np.array([list1, list2])     
print(g)
type(g)

[[9 8 7]
 [6 5 4]]


numpy.ndarray

We could have also constructed the matrix directly as follows. 

In [14]:
g=np.array([[9,8,7], [6,5,4]])     
print(g)

[[9 8 7]
 [6 5 4]]


numpy.ndarray

In the next example, we create a  matrix with 3 rows. 

In [18]:
h=np.array([[1,2],[0,3],[1,1]])
print(h)

[[1 2]
 [0 3]
 [1 1]]


Note that all rows in the 2-dimensional array should have the same length. If not, we get an error message.

In [19]:
m=np.array([[1,2,3],[1,2]])

<ipython-input-19-9dffc3f36ea9>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  m=np.array([[1,2,3],[1,2]])


## 2.3 Higher-dimensional arrays.   <a class="anchor" id="higher-dimension"></a>

We have shown how to create 1-dimensional and 2-dimensional arrays. In fact, we can create arrays of arbitrary dimension, that is, tensors. Next we show an example of a 3-dimensional array. In this case, the elements are 2-dimensional arrays. 

In [20]:
h=np.array([[[1,2],[1,3]],[[0,2],[3,-2]]])
print(h)

[[[ 1  2]
  [ 1  3]]

 [[ 0  2]
  [ 3 -2]]]


In this manual, we will focus on vectors (1-dimensional arrays) and matrices (2-dimensional arrays). 

## 2.4 The empty array of arbitrary size.   <a class="anchor" id="emptyarray"></a>

For programming purposes, it will be helpful to create an empty array of a given size. Next we show an example. We use the function np.empty( ). The first argument of this function provides the size of the array, which in this case is a matrix of size 2x3. 

In [33]:
e=np.empty([2,3], dtype='object')
print(e)

[[None None None]
 [None None None]]


In [35]:
f=np.empty([3,4], dtype='object')
print(f)

[[None None None None]
 [None None None None]
 [None None None None]]


## 2.5 Generating a random array.  <a class="anchor" id="random"></a>

NumPy contains a module that allows working with random matrices. 

First thing we import this module.

In [29]:
from numpy import random

Now we show how to generate a random number. We first use the function random.rand() that produces a random float number between 0 and 1 using the UNIFORM distribution.

In [30]:
x = random.rand()        
print(x)

0.5876154592562154


The function random.randn()  produces a random float number between 0 and 1 using the NORMAL distribution.

In [31]:
y=random.randn()
print(y)

-0.9607764873161277


The function random.randint(s) produces a random integer number in the interval 0-s.

In [32]:
z = random.randint(10)          # random integer number between 0 and 10
print(z)

4


We can use the three functions introduced above to produce arrays with random entries. In the first example, we produce a matrix of size 2x3 whose entries are random numbers in the interval (0,1) using a uniform distribution.

In [173]:
A=np.random.rand(2,3)
print(A)

[[0.5780097  0.04880223 0.52879568]
 [0.45431427 0.9965027  0.55277491]]


In the next example, we produce another 2x3 matrix. But the entries of this matrix  are random numbers in the interval (0,1) using a normal distribution.

In [89]:
B=np.random.randn(2,3)
print(B)

[[ 0.40704109 -1.77773518  0.34418292]
 [ 0.04330954  0.60925164 -1.37858772]]


In the last example, we produce a 3x2 matrix whose entries are random integers in the interval (0,10).

In [90]:
C=np.random.randint(10, size=(3,2))
print(C)

[[6 7]
 [7 0]
 [0 1]]


## 2.6 Transforming the data type of the elements of an array. <a class="anchor" id="arraysdata"></a>

The function np.array allows an extra argument to specify the data type of its elements as well as the size of the data  (number of bits size or bytes lengths). The NumPy library uses the following data types aside of the data types that we introduced in the Jypiter notebook about basic programming in Python:

i - integer

b - boolean

f - float

c - complex float

S - string

u - unsigned integer

We recall that the usual datatypes: int, float, bool, complex, str,... can also be used. 

In our first example, we specify that the array will have float entries. We can check the data type of the entries by using the function arr.dtype( ), where arr is the name of the array. 

In [27]:
a=np.array([1,2,3,4], dtype='f')
print(a)
a.dtype

[1. 2. 3. 4.]


dtype('float32')

In our next example, we have a vector b whose entries are float numbers and we transform it into another vector with integer entries. These entries are obtained by computing the floor of the entries of b. 

In [302]:
b=np.array([1.34, 3/4, 3, 1/7], dtype='i')
print(b)
b.dtype

[1 0 3 0]


dtype('int32')

We note that a number follows the type of an array in the two previous examples. Those numbers give the number of bits used to represent the array. We can change the number of bits by specifying how many bits should be used for each element. Here is an example. 

In [92]:
a=np.array([1,2,3,4], dtype='f8')
print(a)
a.dtype

[1. 2. 3. 4.]


dtype('float64')

In [305]:
b=np.array([1.34, 3/4, 3, 1/7], dtype='i2')
print(b)
b.dtype

[1 0 3 0]


dtype('int16')

Let us now show how to identify if an entry of an array is zero or not by transforming the array into another one with boolean entries. 

In [158]:
c=np.array([1,2,0,4], dtype='bool')
print(c)
c.dtype

[ True  True False  True]


dtype('bool')

This goal could have also been achieved with the function np.nonzero, which returns the indices of the nonzero entries in the array.

In [160]:
arr=[1,2,0,4]
np.nonzero(arr)

(array([0, 1, 3]),)

The function np.count_nonzero provides the number of nonzero entries. 

In [161]:
np.count_nonzero(arr)

3

# 3. DIMENSION, SHAPE, AND SIZE OF AN ARRAY <a class="anchor" id="dimshapesize"></a>

## 3.1 Dimension of an array <a class="anchor" id="dimension"></a>

We have shown in the previous section examples of 0-dimensional, 1-dimensional, 2-dimensional, and 3-dimensional arrays, or equivalently, numbers, vectors, matrices, and tensors of dimension 3. 

Notice that 1-dimensional arrays can be seen as arrays whose elements are 0-dimensional arrays. Similarly, 2-dimensional arrays are arrays whose elements are 1-dimensional arrays, etc. 

The NumPy library provides a way of  determining the dimension of an array as we show next. 

In [44]:
a=np.array(3)
a.ndim

0

In [45]:
b=np.array([1,2,3,4])
b.ndim

1

In [46]:
c=np.array([[9,8,7],[6, 5, 4]]) 
c.ndim

2

In [57]:
d=np.array([[[1,2,0],[1,3,0]],[[0,1,2],[0,1,2]]])
d.ndim

3

## 3.2 Shape of an array <a class="anchor" id="shape"></a>

The shape of an array is the number of elements in each dimension. This is a generalization of the idea of size of a matrix. It is not the same to have a matrix with 3 rows and 2 columns (a 3x2 matrix) than a matrix with 2 rows and 3 columns (a 2x3 matrix). Python offers a way of checking the shape of an array. It produces a tuple, each of its entries being the number of elements in each dimension.

Reusing the examples in the previous section, we have:

In [49]:
a.shape

()

In [54]:
e=np.array([3])
e.shape

(1,)

In [55]:
b.shape

(4,)

In [56]:
c.shape

(2, 3)

In [58]:
d.shape

(2, 2, 3)

Note that ( ) means a 1x1 array of dimension zero, (1,) means a 1x1 array of dimension 1,  and (4, ) means a 4x1 array (of dimension 1). 

## 3.3 Size of an array.  <a class="anchor" id="size"></a>

By size we mean the total number of elements in an array. It is the product of the entries in the "shape" tuple. 

Let us reuse the examples in the previous two sections. 

In [61]:
print(a.size)
print(e.size)
print(b.size)
print(c.size)
print(d.size)

1
1
4
6
12


## 3.4 Reshaping an array  <a class="anchor" id="reshaping"></a>

Reshaping an array means changing its shape. This can be done by increasing its dimension, reducing its dimension, or changing the number of elements in each dimension. 

Let us see some examples. In the first one, we transform a 1-dimensional array of size 6 into a 2x3 array. 

In [63]:
A=np.array([1,2,3,4,5,6])
A2=A.reshape(2,3)
print(A2)

[[1 2 3]
 [4 5 6]]


Notice that, when reshaping, the size of the array cannot change. The array A introduced above has size 6. Next we show we cannot reshape it into an array of size 4. 

In [64]:
A3=A.reshape(2,2)
print(A3)

ValueError: cannot reshape array of size 6 into shape (2,2)

In [65]:
A4=A.reshape(3,3)
print(A4)

ValueError: cannot reshape array of size 6 into shape (3,3)

Let us look at another example. 

In [66]:
B=np.array([[1,1], [2,3],[2,-1]])
B2=B.reshape(2,3)
print(B2)

[[ 1  1  2]
 [ 3  2 -1]]


In order to reshape a multidimensional array into a 1-dimensional array, we can use the following code.

In [67]:
E=c.reshape(-1)
print(E)

[9 8 7 6 5 4]


# 4.  ARRAY INDEXING AND SLICING.  <a class="anchor" id="indexing-slicing"></a>

As with lists, we can access specific elements of an array. Also as with lists, indices start with 0, that is, the first element has index 0, the second element has index 1, etc. Alternatively, we can access a few elements of an array, which is called slicing. 



## 4.1 Indexing   <a class="anchor" id="indexing"></a>

In our first example, we give a 1-dimensional array and show how to extract the first element. 

In [68]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[0]

1

Now we extract the 4th element. 

In [69]:
arr[3]

4

As it happens with lists, we can use negative indexing. The element with index -1 is the last element in a 1-dimensional array.

In [70]:
arr[-1]

9

In [71]:
arr[-2]

8

For higher-dimensional arrays, we can access a particular element by providing its location. For example, let us consider a 2-dimensional array (i.e. a matrix). Let us extract the element in 2nd row and 3rd column. 

In [74]:
arr2=np.array([[1,2,3,4],[0, 1,-1,2]])
print(arr2)

[[ 1  2  3  4]
 [ 0  1 -1  2]]


In [75]:
print(arr2[1,2]) 

-1


Let us extract now the element in the first row and fourth column. 

In [76]:
arr2[0,3]         

4

An alternative way of obtaining the same element by using negative indexing is as follows. 

In [77]:
arr2[0,-1]

4

## 4.2 Slicing    <a class="anchor" id="slicing"></a>

We can also extract a number of consecutive elements from a 1-dimensional array as if it was a list. 

In the next example, we extract the elements in positions 2-5.

In [78]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5])

[2 3 4 5]


If we want to extract all the elements starting at a given one, we don't have to specify the last index. In the next example we extract all elements in the array "arr" starting with the second one.  

In [79]:
print(arr[1:])

[2 3 4 5 6 7 8 9]


And we can skip elements using the code arr[start:stop:step]. For example, we can extract every other element between the 2nd and the 7th element as follows.

In [80]:
print(arr[1:7:2])

[2 4 6]


Given a 2-dimensional array, we can extract a subarray (submatrix) by providing the rows and columns that define that array. Let us extract the submatrix of arr2 consisting of the first two rows and columns. 

In [273]:
arr2=np.array([[1,2,3,4],[0, 1,-1,2]])
print(arr2[0:2,0:2]) 

[[1 2]
 [0 1]]


Next we give the submatrix consisting of the two rows and columns 2-4.

In [81]:
print(arr2[0:2,1:])

[[ 2  3  4]
 [ 1 -1  2]]


In the next example we compute the submatrix consisting of columns 2 and 4.

In [275]:
print(arr2[0:2,1:4:2])

[[2 4]
 [1 2]]


Finally, we construct a random matrix of size 4x6 and extract the submatrix in rows 1, 2, 4 and columns 2 and 6. 

In [87]:
arr3=np.random.rand(4,6)
print(arr3)

[[0.10216049 0.11388275 0.55843422 0.00132376 0.74294238 0.29165658]
 [0.98665727 0.64235754 0.71330852 0.94593793 0.39693415 0.04302963]
 [0.90998676 0.71613566 0.75375494 0.59361979 0.7206893  0.86999549]
 [0.71676153 0.23479509 0.28278084 0.08157076 0.92474579 0.23059051]]


In [88]:
arr3[[0,1,3]][:,[1,5]]

array([[0.11388275, 0.29165658],
       [0.64235754, 0.04302963],
       [0.23479509, 0.23059051]])

# 5. ARRAY ITERATION <a class="anchor" id="iteration"></a>

Allows us to go through the elements of an array one by one using FOR loops. 

In the first example, we print out the elements of a 1-dimensional array. 

In [178]:
a=np.array([2,3,5,7,9,0])

for x in a:
    print(x)

2
3
5
7
9
0


In our next example, we consider a matrix. We print the two elements of the array, namely, the two rows of the corresponding matrix.

In [91]:
b=np.array([[1,2,3], [0,2,-1]])
for x in b:
    print(x)

[1 2 3]
[ 0  2 -1]


Next we print out the elements of a matrix one by one and rown by row. 

In [92]:
c=np.array([[1,2,3], [0,2,-1]])


for x in c:
    for y in x:
        print(y)

1
2
3
0
2
-1


# 6. CONCATENATION OF ARRAYS  <a class="anchor" id="concatenation"></a>

In this section, we study how to concatenate or stack two arrays. This can be done in different ways.  Let us see a few examples. 

In our first example, we consider two 1-dimensional arrays. In order to concatenate them,  we use the code

np.concatenate ((a,b)), where a and b are the two arrays we want to concatenate. 

In [93]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6 7 8]


Since a and b have the same length we can also stack them. We  use the function np.stack. Note that we can stack the two arrays vertically or horizontally as we show next. 

In [94]:
d=np.stack((a,b), axis=0)
print(d)

[[1 2 3 4]
 [5 6 7 8]]


In [95]:
e=np.stack((a,b),axis=1)
print(e)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


The np.concatenate function can also be used with arrays of higher dimension. Let us see an example. Note that the concatenation of two 2x3 matrices produces a 4x3 matrix, that is, it concatenates them vertically. 

In [96]:
a=np.array([[1,2,3],[4,5,6]])
c=np.array([[7,8,9],[10,11,12]])
d=np.concatenate((a,c))
print(d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


This is equivalent to concatenating using the 0 axis. 

In [97]:
f=np.concatenate((a,c), axis=0)
print(f)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


If we use np.concatenate over the axis=1, we get a 2x6 matrix, the horizontal concatenation. 

In [98]:
g=np.concatenate((a,c), axis=1)
print(g)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


The np.stack applied to two matrices produces a 3D-array. Let us see an example. 

In [99]:
g=np.stack((a,c), axis=0)
print(g.shape)

(2, 2, 3)


In [100]:
print(g)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [101]:
e=np.stack((a,c), axis=1)
print(e.shape)

(2, 2, 3)


In [102]:
print(e)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


We could have also used the functions np.hstack and np.vstack instead of np.concatenate as we show next. The first function concatenates horizontally while the second one does is vertically.

In [103]:
h=np.hstack((a,c))
print(h)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [105]:
v=np.vstack((a,c))
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# 7. SORTING ARRAYS   <a class="anchor" id="sorting"></a>

The function np.sort(a) can be used to sort a 1-dimensional with numerical entries in increasing order.

In [155]:
a=np.array([10,2,30,4,50,6])
np.sort(a)

array([ 2,  4,  6, 10, 30, 50])

When applied to 2-dimensional arrays, the function np.sort sorts the elements of each row in increasing way.

In [122]:
b=np.array([[3,2,5], [1,5,3]])
np.sort(b)

array([[2, 3, 5],
       [1, 3, 5]])

In [136]:
c=np.array([[3,2,1],[9,8,7], [6,5,4]])
np.sort(c)

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

For 2-dimensional arrays, we can sort the elements of a matrix in other ways using an appropriate second argument. 

In the first example, we first reshape the matrix to a vector and then order its elements in increasing order.

In [123]:
np.sort(b, axis=None) 

array([1, 2, 3, 3, 5, 5])

In [137]:
np.sort(c, axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In our next example we reorder the columns in increasing way.

In [138]:
np.sort(b, axis=0)

array([[1, 2, 3],
       [3, 5, 5]])

When we use as second argument axis=1, we obtain the same result as when we don't have a second argument. See above. 

In [126]:
np.sort(b, axis=1)

array([[2, 3, 5],
       [1, 3, 5]])

In [139]:
np.sort(c, axis=1)

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

The function np.argsort provides the indices that would order an array. Let us give an example with a 1-dimensional array.

In [143]:
a=np.array([10,2,30,4,50,6])
print(np.sort(a))
print(np.argsort(a))

[ 2  4  6 10 30 50]
[1 3 5 0 2 4]


Now we look at a 2-dimensional array. 

In [144]:
c=np.array([[3,2,1],[9,8,7], [6,5,4]])
print(np.sort(c, axis=None))
print(np.argsort(c, axis=None))

[1 2 3 4 5 6 7 8 9]
[2 1 0 8 7 6 5 4 3]


In [150]:
c=np.array([[3,2,1],[9,8,7], [6,5,4]])
print(np.sort(c, axis=0))

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [151]:
print(np.argsort(c, axis=0))

[[0 0 0]
 [2 2 2]
 [1 1 1]]


In [152]:
c=np.array([[3,2,1],[9,8,7], [6,5,4]])
print(np.sort(c, axis=1))

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [153]:
print(np.argsort(c, axis=1))

[[2 1 0]
 [2 1 0]
 [2 1 0]]


# 8. CREATING A COPY OF AN ARRAY.   <a class="anchor" id="copy-array"></a>

Now we explore some ways in which we can create a copy of a given array. The first that could come to mind is to use the equal operator.

In [5]:
arr=np.array([[2,3,4],[1, 0, 5]])
arr2=arr

However, the equal operator does not create a new object. It just creates a new variable assigned to the same original object. If we make a change in arr2, the same change will appear in arr. 

In [6]:
arr2[1,1]=4
print(arr2)

[[2 3 4]
 [1 4 5]]


In [7]:
print(arr)

[[2 3 4]
 [1 4 5]]


A good way of producing a copy of an array that can be modified independently is using the function np.copy. Let us see an example. 

In [8]:
arr=np.array([[2,3,4],[1, 0, 5]])
arr3=np.copy(arr)
arr3[1,1]=4
print(arr3)

[[2 3 4]
 [1 4 5]]


In [9]:
print(arr)

[[2 3 4]
 [1 0 5]]


# 9.  UNIVERSAL FUNCTIONS.  <a class="anchor" id="universalfunctions"></a>

These are Python functions defined on arrays. There are  more than 60 universal functions. We focus on the most useful ones. 

## 9.1 Basic component-wise arithmetic operations with arrays.  <a class="anchor" id="operations"></a>

In this section we consider componentwise arithmetic operations on arrays, that is, componentwise addition, subtraction, multiplication, and division. 

The usual symbols + and - can be used to add and subtract arrays of the same shape. 

In [11]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])

print('The sum of a and b is the array', a+b)
print('The difference of a and b is the array',a-b)

The sum of a and b is the array [[ 8 10 12]
 [14 16 18]]
The difference of a and b is the array [[-6 -6 -6]
 [-6 -6 -6]]


The symbols * and / can be used to produce the componentwise product and division of two arrays. 

In [12]:
print(a*b)

[[ 7 16 27]
 [40 55 72]]


In [13]:
print(a/b)

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Notice that for the division arr1/arr2 to exist, arr2 must have no zero entries.

In [15]:
c=np.array([[1,1,3],[0,1,2]])
print(a/c)

[[ 1.  2.  1.]
 [inf  5.  3.]]


<ipython-input-15-c802ee29914e>:2: RuntimeWarning: divide by zero encountered in true_divide
  print(a/c)


Alternative functions for the four basic arithmetic operations described above are np.add, np.subtract, np.multiply, and np.divide.

In [16]:
print(np.add(a,b))

[[ 8 10 12]
 [14 16 18]]


In [17]:
print(np.subtract(a,b))

[[-6 -6 -6]
 [-6 -6 -6]]


In [18]:
print(np.multiply(a,b))

[[ 7 16 27]
 [40 55 72]]


In [19]:
print(np.divide(a,b))

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


## 9.2 Other useful component-wise functions defined on arrays.  <a class="anchor" id="otherfunctions"></a>

Other useful functions are introduced below. .

### Component-wise power

The first function that we present is the power function, which raises the elements of the first array to a power given by the second array. More specifically, given  two matrices a and b (could be vectors) with entries a_{ij} and b_{ij}, respectively, c=a^b is defined as the matrix whose (i,j)th entry is given by  a_{ij}^{b_{ij}}. 

Let us see an example

In [22]:
a=np.array([[1,2],[4,5]])
b=np.array([[7,8],[0,1]])

print(np.power(a,b))

[[  1 256]
 [  1   5]]


We notice that the matrix of exponents can only contain nonnegative entries. 

In [23]:
c=np.array([[0, 1],[-1, 2]])
print(np.power(a,c))

ValueError: Integers to negative integer powers are not allowed.

### The remainder and quotient.

The function np.mod and np.remainder both  provide the remainder of dividing the elements of the first array by the corresponding elements in the second array.

We present an example next. 

In [26]:
a=np.array([[8,2,4],[4,5,6]])
b=np.array([[2,8,1],[10,11,12]])
print(np.mod(a,b))

[[0 2 0]
 [4 5 6]]


In [27]:
print(np.remainder(a,b))

[[0 2 0]
 [4 5 6]]


The funcion np.divmod provides both the quotient and the remainder when the elements of the first array are divided by the elements of the second array.

In [28]:
print(np.divmod(a,b))

(array([[4, 0, 4],
       [0, 0, 0]]), array([[0, 2, 0],
       [4, 5, 6]]))


### The absolute value of an array.

The function np.absolute computes the modulus of the entries of an array.

In [156]:
a=np.array([2, -3, 2+3j])
print(np.absolute(a))

[2.         3.         3.60555128]


### The component-wise square root 

This function computes the square root of the entries of a matrix. 

In [40]:
b=np.array([[1, 2],[0,3]])
print(np.sqrt(b))

[[1.         1.41421356]
 [0.         1.73205081]]


In order to compute the square root of a matrix with negative entries, we can use the function np.emath.sqrt

In [43]:
c=np.array([[1, -2],[0,3]])
print(np.emath.sqrt(c))

[[1.        +0.j         0.        +1.41421356j]
 [0.        +0.j         1.73205081+0.j        ]]


### The component-wise square of a matrix

Computes the square of all the entries of a matrix. 

In [45]:
c=np.array([[1, -2],[0,3]])
print(np.square(c))

[[1 4]
 [0 9]]


### The component-wise reciprocal of a matrix 

Clearly, all entries of the matrix must be nonzero.

In [48]:
c=np.array([[1, -2],[1/3,3]])
print(np.reciprocal(c))

[[ 1.         -0.5       ]
 [ 3.          0.33333333]]


### The complex conjugate of a matrix.

It computes the conjugate of all the entries in the matrix.

In [52]:
a=np.array([[2, -3, 2+3j],[4+1j, 3j, -3]])
print(np.conj(a))

[[ 2.-0.j -3.-0.j  2.-3.j]
 [ 4.-1.j  0.-3.j -3.-0.j]]


### The row and column sums

These are not component-wise operations but are extensively used when programming linear algebra algorithms. 

The functions np.sum and np.prod compute, respectively, the sum and the product of all the elements in an array.

In [29]:
a=np.array([2, -3, 2+3j])
print(np.sum(a))

(1+3j)


In [30]:
print(np.prod(a))

(-12-18j)


 A second argument can be added to the previous two functions if we want to add the elements by rows or columns. 
 
 When using np.sum, if we choose axis=0 as the second argument, we get the column sum. 

In [31]:
b=np.array([[7,8,9],[10,11,12]])
print(np.sum(b, axis=0))

[17 19 21]


If we choose axis=1, we get the row sum. 

In [32]:
print(np.sum(b, axis=1))

[24 33]


When using np.prod, if we choose axis=0 as the second argument, we get the column product

In [139]:
print(np.prod(b, axis=0))

[ 70  88 108]


If we choose axis=1, we get the row product.

In [33]:
print(np.prod(b, axis=1))

[ 504 1320]


# 10. THE NUMPY LINALG FUNCTIONS  <a class="anchor" id="linalg"></a>

In this section we focus on functions that are directly related with linear-algebra related objects and algorithms.

In Linear Algebra, there is a lot of focus on matrices. NumPy offers a special code for constructing matrices, namely, np.mat

In [125]:
A=np.mat('1,2,3;0, 1,-4')
print(A)

[[ 1  2  3]
 [ 0  1 -4]]


## 10.1  Special matrices.  <a class="anchor" id="special"></a>

We show here how to construct a matrix of given size with zero entries, or with all entries equal to one, or 

We start by showing how to construct a matrix of all zeros.

In [55]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Next we construct a matrix of all ones. 

In [56]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

If we would like to construct a matrix with equal entries, not necessarily ones, we use the command np.full

In [61]:
np.full((2,3), 9)

array([[9, 9, 9],
       [9, 9, 9]])

Next we show how to create an identity matrix of a given size.  

In [58]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

The identity matrix is a particular case of diagonal matrix. 

In many occassions it is useful to construct a diagonal matrix whose main diagonal entries are known. 

In [60]:
np.diag([3, 2, 8])

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 8]])

## 9.2 Operations with matrices and vectors. <a class="anchor" id="operations-matrices"></a>

In the previous section we showed how to implement component-wise operations on arrays. Now we present other operations with vectors and matrices that are not component-wise. 

### The dot product and matrix multiplication

We start with the dot product of two vectors.

In [100]:
a=np.array([1,2,3])
b=np.array([2,3,0])

print(np.dot(a,b))

8


In [101]:
a.dot(b)

8

The function np.dot can also be used to compute the row-column multiplication of two matrices. They must be compatible for multiplication, that is, if a is a matrix of size (shape) 3x2, and we want to compute ab, then b must be a matrix of size 2xp, for some positive integer p.  

In our example, we consider a matrix c of size 3x2 and a matrix d of size 2x3. Note that both cd and dc are well defined. 

In [102]:
c=np.array([[3,2,1],[0, -1, 2]])
d=np.array([[1,2], [0,1], [-1, 3]])
print(c.shape)
print(d.shape)

(2, 3)
(3, 2)


In [103]:
print(np.dot(c,d))

[[ 2 11]
 [-2  5]]


In [104]:
print(np.dot(d,c))

[[ 3  0  5]
 [ 0 -1  2]
 [-3 -5  5]]


 Next we give an alternative function for matrix multiplication that is more recommendable than the function np.dot for numerical purposes. 

In [105]:
c=np.array([[1,2,3], [0,1,2]])
d=np.array([[1,2], [3,4], [5,6]])
np.matmul(c,d)

array([[22, 28],
       [13, 16]])

Next we show another possible way of multiplying matrices. 

In [74]:
print(c@d)

[[22 28]
 [13 16]]


If we use the notation np.mat, then we can also multiply matrices using the standard notation a*b.

In [107]:
c=np.mat('1,2,3;0,1,2')
d=np.mat('1,2; 3,4; 5,6')
c*d

matrix([[22, 28],
        [13, 16]])

### Matrix powers and the inverse of a matrix.

Next we see how to find a power of a matrix, where the exponent is any integer. We first import the module matrix_power from the library numpy.linalg. Notice that this function can only be applied to square matrices. 

In [75]:
from numpy.linalg import matrix_power

If the exponent is zero, we get the identity matrix. 

In [76]:
A=np.array([[1,2,3], [0,1,2], [1,1, -1]])
print(matrix_power(A, 0))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


If the exponent n is positive, we get the nth power of the matrix. 

In [77]:
print(matrix_power(A,2))

[[4 7 4]
 [2 3 0]
 [0 2 6]]


If the exponent is -1, we get the inverse of the matrix, if it exists. 

In [78]:
B=matrix_power(A,-1)
print(B)

[[ 1.5 -2.5 -0.5]
 [-1.   2.   1. ]
 [ 0.5 -0.5 -0.5]]


Next we confirm that B is the inverse of A. 

In [79]:
np.matmul(A,B)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Finally, if the exponent n is negative, the function first computes the inverse of the matrix and then its (-n)th power.

In [80]:
print(matrix_power(A,-2))

[[ 4.5 -8.5 -3. ]
 [-3.   6.   2. ]
 [ 1.  -2.  -0.5]]


Alternative ways of computing the inverse of a matrix are presented next. 

In [115]:
from numpy.linalg import inv
a = np.array([[1, 2], [3, 4]])
print(inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


If we use the notation np.mat, the inverse function produces another matrix.

In [116]:
b=np.mat('3,2;1,0')
print(inv(b))

[[ 0.   1. ]
 [ 0.5 -1.5]]


### The transpose and conjugate transpose of an array.

The transpose of an array can be computed with the function a.T

In [81]:
h=np.array([[1,2,3],[3,4,5]])
print(h)

[[1 2 3]
 [3 4 5]]


In [82]:
print(h.T)

[[1 3]
 [2 4]
 [3 5]]


In order to compute the conjugate transpose, we use the notation np.mat.H

In [108]:
h2=np.mat([[3, 1+2j, -5-3j],[4j, 5, 2+1j]])
print(h2)

[[ 3.+0.j  1.+2.j -5.-3.j]
 [ 0.+4.j  5.+0.j  2.+1.j]]


In [109]:
h3=h2.H
print(h3)

[[ 3.-0.j  0.-4.j]
 [ 1.-2.j  5.-0.j]
 [-5.+3.j  2.-1.j]]


## 9.3 The determinant of a matrix and its trace. <a class="anchor" id="determinant-trace"></a>

The function np.linalg.det calculates the determinant of a square matrix.

In [111]:
A=np.mat('3,2,1;0,1,2; 1, 1, 1')
print(A)

[[3 2 1]
 [0 1 2]
 [1 1 1]]


In [112]:
np.linalg.det(A)

0.0

The trace of a matrix is the sum of its main diagonal entries. 

In [113]:
np.trace(A)

5

## 9.4 Rank of a matrix  <a class="anchor" id="rank"></a>

We use a numpy.linalg function to compute the rank of a matrix. We need to import this function before it can be used. 

In [117]:
from numpy.linalg import matrix_rank
matrix_rank(np.eye(4)) 

4

In [118]:
A=np.diag([3,2,0])
matrix_rank(A)

2

# 10. The functions linspace and arange  <a class="anchor" id="linspace"></a>

Both of these functions allow to create a sequence of numbers. The main difference between them is that linspace allows to specify the number of steps while arange gives the option of specifying the size of the steps. 

Let us see a few examples. 

The code np.linspace(a,b,n) creates a sequence of n evenly spaced values between a and b. 

In [124]:
np.linspace(0, 10, 9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [120]:
np.linspace(3.7, 9.8, 10)

array([3.7       , 4.37777778, 5.05555556, 5.73333333, 6.41111111,
       7.08888889, 7.76666667, 8.44444444, 9.12222222, 9.8       ])

In [ ]:
The code np.arange(a,b,s) provides a sequence of values between a and b spaced by s.

In [122]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [123]:
np.arange(3.7, 12.9, 0.1)

array([ 3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,
        4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,
        5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,
        7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ,
        8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ,  9.1,
        9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. , 10.1, 10.2,
       10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. , 11.1, 11.2, 11.3,
       11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1, 12.2, 12.3, 12.4,
       12.5, 12.6, 12.7, 12.8])

These functions will be particularly important when we learn how to plot functions. 